"""Render source-backed seal and final reports; does not fit or score."""
import json,sys
import pandas as pd
from prepare import ROOT,E0,REPO,sha,save

def write(name,parts):(ROOT/name).write_text('\n\n'.join(parts)+'\n')
def table(rows,keys):
    return '| '+' | '.join(keys)+' |\n| '+' | '.join(['---']*len(keys))+' |\n'+'\n'.join('| '+' | '.join(str(r.get(k,'')) for k in keys)+' |' for r in rows)
def main():
    p=json.loads((ROOT/'configs/protocol.json').read_text());m=json.loads((ROOT/'configs/data_manifest.json').read_text());e=json.loads((ROOT/'configs/event_manifest.json').read_text())
    strata=pd.Series([x['stratum'] for x in e]).value_counts().to_dict()
    write('EXECUTION_SEAL.md',['# E1 execution seal — prospective','**GO only for the fixed PCA/SPE and CAUSAL_LSTM_REFERENCE panel after this seal is committed, pushed and remote-verified. No detector training/inference has run during seal construction.**','[Issue #26](https://github.com/kuo1234/xlstm_anomaly/issues/26) authorizes E1 independently of stopped M0/D0/E0 hypotheses. Historical results remain unchanged. This is causal score generation/lifecycle falsification, not method design.',f'19 raw traces across apps6/9/10:12 whole normal traces,6 primary-type disturbed traces,1 crash control. Selected strata: {strata}. All109 GT events remain in [event manifest](configs/event_manifest.json), with selected/excluded reasons. Ground-truth SHA256: `'+sha(REPO/'data/exathlon_e0_sources/ground_truth.csv')+'`. Exact archive/blob/CSV/selected-column identities and prepared-array hashes are [raw audit](provenance/raw_audit.json). No anomaly score was used in selection.','Native1s, official19-feature definitions through a separately documented causal variant; no15s phase mixing. Global fit-only scaler. First duplicate row; integer timestamps retained; bounded forward fill only for histories/features; missing targets never receive primary scores. Initial missing values are unavailable. Same-time active executor averaging precedes fill.', 'Fixed seed21; PCA8 components; one-layer LSTM hidden32/history32, Adam1e-3,10epochs,128batch, norm-clip1; fit stride8/max8192 windows. Final epoch only, validation is diagnostic. No early stopping, sweep or anomaly model selection. C is excluded prospectively for unsealed native runtime compatibility; no replacement. [Complete protocol](configs/protocol.json).','Material effect: trace-macro median Delta_effect >=1 normal-calibration IQR in both families; each eligible type/app median positive; stationary event-balanced ramp<0.5IQR, excess-normal contrast>=1IQR, effect-only excess>=0.1 and>=50% complete RCI alarm events. Raw eligibility>=95% native phase score coverage, RCI>=30/EEI>=10/pre>=30 observations; at least50% selected events,2types/3apps, and>=5 matched normal controls for a majority. These are prospective engineering margins, not statistical guarantees.','Protocol bugs require STOP, pushed amendment and exposure disclosure before changed execution. Negative gates cannot authorize type/model/threshold/polarity changes. After results, commit/push/reply Issue and STOP.'])
    write('DATA_SPLIT.md',['# Whole-trace normal split',table(m,['trace','role','sha256']),'Four smallest single-ZIP normal archives per app are selected by released byte size and numeric ID tie; their ascending numeric IDs assign fit/validation/calibration/normal_control. Multipart traces are excluded before outcomes to bound acquisition. This yields one trace per app per role. App6’s selected normal contexts have low rates; app9/app10 differ. It is a bounded global reference, not matched-context training.','No random-window overlap between roles. scaler/PCA/LSTM only use fit traces, every one officially undisturbed. Validation diagnostics cannot choose epoch/model. Whole independent calibration traces set normalq.995 and IQR; normal_control traces only supply FPR and duration controls. Disturbed labels are read only by the evaluator after training. Exact timestamps/features/arrays are independently hashed in the manifests.','Offline frozen-model causal input availability is tested; this is not a claim of chronologically deployed2018 model fitting. Shared cluster executions and app/type resource confounds remain dependencies.'])
    write('CAUSAL_PREPROCESSING.md',['# Causal preprocessing contract','[Feature definitions](configs/features.json) derive from pinned Exathlon SPARK_BUNDLES[0]:3 delay gauges,10 backward-differenced driver/node metrics,6 backward-differenced active-executor means. This is explicitly a causal variant, not native feature-pipeline reproduction.','Source row order must be nondecreasing. Retain first duplicate timestamp, record duplicate/gap counts. Insert integer1s history grid; target-observed mask stays false at missing source times. Sentinel−1/nonfinite values are missing. Never backward fill/interpolate/normalize test traces. Forward fill at most5 seconds; unavailable initial/long-gap values remain NaN. Average active raw executor slots before causal fill so inactive slots do not become active. Derivatives use t minus t−1.','PCA targets need an observed timestamp and finite current19 features. LSTM requires32 finite past feature vectors plus observed finite current target. History fill is allowed; scoring a missing target is forbidden. No window crosses a trace boundary. All missing score support is explicit. Training mean/population std from fit rows; zero std becomes1, no test-informed clipping.','Artificial prefix-invariance tests include missing timestamps, sentinels and duplicates. They exercise transformations only before seal; no detector inference occurs before pushed seal. Native full-test scaling, backfill and future-enclosing-window AE readout are not used.'])
    write('BASELINE_CONTRACT.md',['# Fixed two-family panel',table([{'baseline':'PCA_SPE','family':'non-neural pointwise reconstruction','settings':'8components, float64 SVD, standardized SPE/MSE'},{'baseline':'CAUSAL_LSTM_REFERENCE','family':'one-step recurrent forecast','settings':'19→32 LSTM1layer→19 linear; W32;10epochs; Adam1e-3'}],['baseline','family','settings']),'LSTM prediction consumes only t−32..t−1; score is residual when target t arrives. This is a named reference, not native TensorFlow LSTM reproduction. PCA score uses current observed t. Both fit once, same normal scaler/roles/seed; their objectives/optimization differ and there is no parameter-budget parity claim.','DIVAD pinned TranAD has custom encoder/decoder forward signatures without modern PyTorch2.9 causal kwargs. The older native environment/framework parity and compatibility overlay have not been sealed. BaselineC NOT_RUN is fixed prospectively under Issue26’s optional-C rule; no alternate model will be selected. [Static runtime evidence](provenance/runtime.json).','Final checkpoint only; no anomaly-trained tuning, early stopping or epoch choice. Fixed normal validation loss remains visible so failure to learn is not hidden. A small single-seed reference panel can falsify its proposed shared mechanism but cannot establish universal detector behavior.'])
    write('SCORE_CONTRACT.md',['# Score availability and lineage','Every score-table row contains raw_trace_id,target_timestamp,available_at,score,baseline_id,checkpoint_hash,preprocessing_hash,scaler_hash,fit_split_id,calibration_split_id,target_observed,role. Native timestamp is the target; available_at=target. NaN marks missing score rather than zero/normal. Primary finite score requires available_at<=target and observed target.','PCA computes with current t; LSTM forecasts before target then residual is available on target arrival. No future averaging, readout shifts, smoothing, EWMA or warm-up fill. Full history is bounded at the target, independent trace state resets. Post-seal tests compare actual model scores under a changed future suffix and independently rederive PCA/LSTM scores.','Complete compressed score arrays/checkpoints/scaler live in ignored data/exathlon_lifecycle_e1. Tracked artifact ledger hashes every output; scripts regenerate the files from pinned raw identities. Serialized-container hashes and canonical array hashes are distinguished. Deployment-source clocks/sensor transport delay are unknown; availability is the mathematical observation contract, not measured wall-clock latency.'])
    write('METRICS.md',['# Frozen primary metrics and gates','RCI=[start,end], EEI=(end,effect_end], pre/recovery300s. Unknown, point, crash descriptors, no-impact CPU and missing EEI stay excluded/secondary. Other event supports are removed from unique attribution. Native missing targets remain N/A; no interval widening.', 'Z_RCI=(medianRCI−medianpre)/IQR_normal_cal; Z_EEI=(medianEEI−medianpre)/IQR_normal_cal; Delta_effect=Z_EEI−Z_RCI. Degenerate IQR→N/A. Raw eligibility and1IQR material margin are in [protocol](configs/protocol.json). No p-value/significance claim. Event medians aggregate first by trace; retain type/app counts and shared-run dependence.', 'Effect-only: no eligible RCI alarm plus>=1 EEI alarm, only complete expected native RCI score coverage; otherwiseN/A. Root observed alarms and alarm-time fractions remain descriptive under incomplete support. Delay requires complete native RCI/EEI and no overlap. Threshold normal-calibration q.995, linear; app-normal thresholds secondary, deployment app ID known. No per-trace oracle or test-label tuning.','Heldout-normal controls preserve each event’s RCI/EEI durations with300s pre:10 equally spaced placements per heldout trace when available, no score-based selection, overlapping controls are not independent samples. Same-trace pre-controls end301s before event, exclude labeled contamination. No-impact post60s is explicitly pseudo-effect, not missing GT EEI fabricated. Crash only tests censoring.','Controls, normalFPR, raw continuity, fragments, dropout/alarm fraction and duration-matched observed capture are all reported. Frozen gate prioritizes execution/resolution; threshold-only excess before no-gap; then model-specific, context confounds, and positive corroboration. Context verdict describes confounding, not a causal proof. Positive mechanism gate never authorizes novelty or method design.'])
    final='--final' in sys.argv
    if final:
        g=json.loads((ROOT/'results/final_gate.json').read_text());tr=json.loads((ROOT/'results/training.json').read_text());normal=json.loads((ROOT/'results/normal_scores.json').read_text())
        ag=json.loads((ROOT/'results/aggregations.json').read_text());ev=pd.read_json(ROOT/'results/event_metrics.json');controls=pd.read_json(ROOT/'results/control_metrics.json')
        burden=[]
        for b in p['baselines']:
            cr=controls[(controls.baseline==b)&controls.control_kind.eq('stationary_normal')&controls.raw_eligible]
            pr=ev[(ev.baseline==b)&ev.stratum.eq('primary')&ev.raw_eligible]
            burden.append({'baseline':b,'primary_observed_root_capture':float(pr.rci_capture_observed.mean()),'normal_event_balanced_observed_root_capture':float(cr.groupby('event_id').rci_capture_observed.mean().mean()),'primary_median_root_alarm_fraction':float(pr.rci_alarm_time_fraction.median()),'normal_event_balanced_root_alarm_fraction':float(cr.groupby('event_id').rci_alarm_time_fraction.median().median()),'stationary_controls':len(cr),'pre_event_controls':int(((controls.baseline==b)&controls.control_kind.eq('pre_event')&controls.raw_eligible).sum())})
        save(ROOT/'results/burden_control_summary.json',burden)
        write('RESULTS.md',['# E1 bounded lifecycle falsification results',f'**{g["verdict"]}**. Seal commit `{tr["seal_commit"]}` preceded all model training/inference. No model/metric/type/threshold change after outcome inspection. PCA/SPE and CAUSAL_LSTM_REFERENCE executed once, seed21, native1s,19 features; TranAD NOT_RUN prospectively.','## Raw phase evidence',table(g['family_evidence'],['baseline','primary_events','eligible_events','eligible_types','eligible_apps','trace_macro_Delta','stationary_event_balanced_Delta','paired_normal_excess_Delta','complete_RCI_alarm_events','effect_only_rate','heldout_normal_FPR']),'Trace-macro medians prevent a trace containing many events from automatically dominating. Confidence/significance/population universality are not inferred from dependent event/control counts. Material threshold is1normalIQR, fixed before outcomes. Positive sign alone does not pass.',table(ag,['baseline','group','value','events','traces','trace_macro_Delta','median_Z_RCI','median_Z_EEI']), '## Root capture burden and controls',table(burden,['baseline','primary_observed_root_capture','normal_event_balanced_observed_root_capture','primary_median_root_alarm_fraction','normal_event_balanced_root_alarm_fraction','stationary_controls','pre_event_controls']),'Observed capture is not proof of complete root-time absence. Missing native timestamps censor strict effect-only/delay fields even when phase medians remain eligible. Duration-matched controls overlap and share normal traces; no iid count claims. No-impact pseudo60s post and crash censoring rows are retained in control/event files, not primary.', '## Calibration and continuity',table(normal,['baseline','trace','app','role','median','IQR','global_FPR','app_threshold_FPR']),'Calibration FPR is in-sample descriptive; heldout normal_control FPR is independent. A q.995 calibration quantile does not guarantee0.5% heldout FPR. App-conditioned thresholds were frozen secondary, not selected by test labels. Exact-normal-context support is flagged per event and is not a matched-control claim. Event JSON includes raw score continuity, alarm fragments/run lengths, pre/recovery support and censoring; none implies a novel smoothing method.',f'Runtime: {tr["runtime"]}; {tr["fit_points"]} scaler/PCA fit points; {tr["fit_windows"]} LSTM fit windows; wall time {tr["seconds"]:.1f}s. Final-epoch checkpoint; normal validation losses are [training record](results/training.json). Complete causal score/checkpoint hashes: [artifact ledger](provenance/score_artifacts.json).'])
        write('FINAL_GATE.md',['# E1 final gate',f'**{g["verdict"]}**\n\n`method_design_GO=false`; lifecycle method route '+('STOP.' if g['kill_route'] else 'does not advance to method design.'),g['reason'],'This result applies to the sealed two-family global19-feature single-seed panel and selected apps/traces. It does not prove that all detectors lack root/effect differences or that Exathlon is unusable. Native LSTM/TranAD reproduction and comprehensive model comparisons were not performed. Phase/event exclusions were prospective, not chosen to rescue a result.','Prior-art residual target: phase-specific within-event contrasts with normal burden and causal availability, rather than native union-label AD3. Original Exathlon fragmentation/global separation and DIVAD heterogeneous contexts remain occupied; this experiment establishes no novelty or xLSTM benefit.','Scores and training were actually executed after pushed seal; all tracked outputs, hashes, verification and remaining limits are reported. Preserve the negative gate; do not change models/types/thresholds/polarity/smoothing/point inclusion. Commit/push/reply Issue26; STOP for reviewer.'])
    docs=['EXECUTION_SEAL','DATA_SPLIT','CAUSAL_PREPROCESSING','BASELINE_CONTRACT','SCORE_CONTRACT','METRICS']+(['RESULTS','FINAL_GATE'] if final else [])
    write('README.md',['# Issue26 — Exathlon causal score recovery / lifecycle falsification',('**'+g['verdict']+'; method_design_GO=false; STOP for reviewer.**') if final else '**Execution seal only — no detector training/inference yet. Push and verify this commit before running.**','This is E1 following [E0](../exathlon_semantic_failure_e0/README.md). Historical P4/P5/M0-S/D0/E0 reports are unchanged. Fixed PCA/SPE and a named causal LSTM reference;19 raw traces, native1s, whole-trace normal-only roles; optional TranAD skipped prospectively for unsealed compatibility.','\n'.join('- ['+x+']('+x+'.md)' for x in docs),'Exact executed Python/PyTorch/numpy/pandas versions are in provenance/runtime.json. `prepare.py` downloads/checks pinned archives and derives arrays; pushed seal proof must be created/verified before `run.py`; then `analyze.py`, `document.py --final`, `verify.py --final`. Full raw/checkpoint/score arrays remain ignored; artifact hashes and commands are tracked. No outcome-driven retry/tuning is authorized.'])
    print('documents','final' if final else 'seal')
if __name__=='__main__':
    main()
    if '--final' in sys.argv:
        for name in ['RESULTS.md','FINAL_GATE.md','README.md']:
            path=ROOT/name
            path.write_text(path.read_text()+'\n[Review and limitations](REVIEW_NOTES.md), [verification](provenance/result_verification.json), [independent checks](provenance/independent_checks.json), [verification amendment01](AMENDMENT_01.md) / [amendment02](AMENDMENT_02.md), [figure PDF](results/lifecycle_contrast.pdf).\n')
        path=ROOT/'RESULTS.md';path.write_text(path.read_text()+'\n![Lifecycle contrast](results/lifecycle_contrast.png)\n')
        path=ROOT/'README.md'
        path.write_text(path.read_text()+'''\nCurrent cached-evidence audit commands (repository-root cwd):

```sh
E1_PY=/tmp/m0e-issue22/venv/bin/python
$E1_PY research/exathlon_lifecycle_e1/scripts/verify.py --final
$E1_PY research/exathlon_lifecycle_e1/scripts/independent_checks.py
```

`run.py` intentionally refuses another training run once the remote branch advances beyond its verified execution seal. Full retraining needs a reviewer-authorized new execution branch/seal; a negative result does not authorize a rerun. To recover missing raw/prepared assets, first use E0 `sources.py` to restore its source/ground-truth cache, then E1 `prepare.py`. Complete score arrays/checkpoints remain local ignored assets;38 score hashes and saved-checkpoint hashes are tracked. Metric replay uses cached scores and does not retrain. The final renderer adds descriptive figure/review links and uses the exact executed runtime record (Python3.14.6) instead of an earlier documentation-only3.12 shorthand; no scientific config/execution/metric changes.
''')
