"""Render final evidence and a scientific figure; no changes to frozen metrics."""
import json
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1]
def main():
 rows=json.loads((ROOT/'results/primary_events.json').read_text());control=json.loads((ROOT/'results/controls.json').read_text());g=json.loads((ROOT/'results/gate.json').read_text());verify=json.loads((ROOT/'provenance/verification.json').read_text());recovery=json.loads((ROOT/'results/input_recovery.json').read_text())
 table='| event /app | current-vector availability | strict32-history availability | additional event-time loss | fixed controls |\n|---|---:|---:|---:|---:|\n'+'\n'.join(f'|{r["event_id"]} /{r["app"]}|{100*r["W0_fraction"]:.2f}%|{100*r["W32_fraction"]:.2f}%|{100*r["W32_additional_fraction"]:.2f}pp|{r["eligible_pre_controls"]}|' for r in rows)
 text=['# N2 external observability replication',f'**{g["verdict"]}**. Five controlled holdout events across4 apps pass the prospective25% material margin. Six events were reported; one has0 legal pre-controls and remains unsupported. No event/window/control replacement.',table,'All15 fixed eligible controls have current-vector availability>=98.44%; their history-only additional loss is0 in every control, not only the median. Driver-labelled current-vector availability is43.75–92.06%, while strict32-history availability is4.69–41.27%. These are scoring opportunity fractions, **not alarm recall, fault accuracy, or results from retrained models**.','Changing the finite-history availability requirement on identical fixed inputs blocks25–32 otherwise-current-scorable target instants inside the driver-labelled intervals. In all6 recovery episodes, the first strict32-history opportunity occurs32s after the preprocessed feature vector becomes finite again; one comes after annotation end. This lag is input-feasibility recovery, not measured alarm latency. W8/16 structural diagnostics are reported without model-performance claims.','The data demonstrate a concrete failure mechanism: apparent normal input health can coexist with fault-selective scoring blackout, and history requirements amplify the missingness. The strict policy is conditional on the frozen19-feature causal preprocessing, including5s forward fill; this is not an inherent LSTM/xLSTM limitation or a claim that every partial-observation predictor must abstain.','Controls are annotation-clean pre-event intervals, not independently certified healthy physical units. Known overlap/context flags remain; one app5 executor context is unknown. Spark fault injections, shared cluster runs, one fault family and tiny event counts prevent independent-fleet or significance claims. No future fill, target imputation beyond the frozen policy, weight/threshold change or lifecycle rescue occurred.',f'Execution seal `{g["seal_sha"]}` was pushed/remote-verified before these event/control outcomes. Independent scalar enumeration matches {verify["scalar_full_trace_mask_endpoint_checks"]} complete-trace endpoint contracts and {verify["independent_interval_count_checks"]} interval counts;5 source/array and5 mask hashes,4 boundary/causality tests, controls and gate checks PASS. This is separate code verification by the same agent, not external peer review.','[Prior-art and research positioning](PRIOR_ART.md), [protocol](configs/protocol.json), [all events](results/primary_events.csv), [controls](results/controls.json), [input recovery](results/input_recovery.json), [verification](provenance/verification.json). Method design/novelty GO remain false. The validated result supports a new availability-aware evaluation question; it does not establish detector repair utility.','![Scoring opportunity](results/scoring_opportunity.png)']
 (ROOT/'RESULTS.md').write_text('\n\n'.join(text)+'\n')
 fig,ax=plt.subplots(figsize=(10,5));x=np.arange(len(rows));width=.18
 for j,(w,c) in enumerate([(0,'#2463a5'),(8,'#7ba4bf'),(16,'#dea26a'),(32,'#c3512d')]):ax.bar(x+(j-1.5)*width,[100*r[f'W{w}_fraction'] for r in rows],width,color=c,label='Current vector' if w==0 else f'Finite history{w}s')
 ax.set_ylim(0,105);ax.set_ylabel('Input-feasible scoring targets /annotated targets (%)');ax.set_xticks(x,[f'App{r["app"]}\n{r["event_id"]}'+ ('†' if not r['evaluation_supported'] else '') for r in rows]);ax.legend(ncol=2,fontsize=9);ax.set_title('Fault-selective scoring blackout: fixed-input availability contracts');ax.spines[['top','right']].set_visible(False);ax.grid(axis='y',alpha=.2)
 fig.text(.02,.015,'† No legal pre-controls; reported, excluded from positive gate. Fifteen fixed controls:0 extra history-blocked targets.\nMasks only; no new model scores, alarm recall, method novelty or universal temporal-model claim.',fontsize=8);fig.tight_layout(rect=[0,.09,1,1]);fig.savefig(ROOT/'results/scoring_opportunity.png',dpi=180);fig.savefig(ROOT/'results/scoring_opportunity.pdf');plt.close(fig)
 print('N2 report and figure rendered')
if __name__=='__main__':main()
