"""Render E0 audit evidence. --final adds unmeasured F1-F4 status and one gate."""
import json
from pathlib import Path
import sys
import pandas as pd
from sources import ROOT,RESULT

NATIVE='https://github.com/exathlonbenchmark/exathlon/blob/4101f6087f902fa150e392b65c957976faa84e40/'
DIVAD='https://github.com/exathlonbenchmark/divad/blob/47a0893eff719863e96e1156ea9ed1b4a9b92209/'


def read(name):return json.loads((RESULT/name).read_text())
def table(df):
    def cell(v):
        if pd.isna(v):return 'N/A / unknown'
        if isinstance(v,float):return f'{v:.3f}'
        return str(v).replace('|',' / ')
    return '\n'.join(['| '+' | '.join(map(str,df.columns))+' |','|'+'|'.join(['---']*len(df.columns))+'|']+['| '+' | '.join(cell(v) for v in row)+' |' for row in df.itertuples(index=False,name=None)])
def write(name,parts):(ROOT/name).write_text('\n\n'.join(parts)+'\n')


def main():
    final='--final' in sys.argv
    status=read('source_status.json');types=pd.read_csv(RESULT/'type_summary.csv');normal=pd.read_csv(RESULT/'normal_trace_support.csv');raw=pd.read_csv(RESULT/'raw_sample_audit.csv');aligned=pd.read_csv(RESULT/'raw_event_timestamp_support.csv');coverage=pd.read_csv(RESULT/'type_app_context_coverage.csv');overlap=pd.read_csv(RESULT/'event_overlap.csv');bins=pd.read_csv(RESULT/'phase_bin_support.csv');variation=pd.read_csv(RESULT/'normal_raw_feature_variation.csv')
    write('DATA_GROUND_TRUTH_AUDIT.md',[
        '# Exathlon ground-truth reality check — 2026-10-06',
        f'Official [ground_truth.zip]({NATIVE}data/raw/ground_truth.zip) contains one CSV, seven fields and 109 unique rows. The original trace archive inventory contains 93 native traces: 59 undisturbed and 34 disturbed. The bytes and Git blob/SHA256 are saved in provenance; CSV SHA256 is `{status["source_ground_truth_sha256"]}`. These are measured Spark-cluster telemetry with deliberately injected events, not naturally occurring faults or a dynamical simulation. No label is inferred from TSB filenames.',
        '| Field | Meaning / audited rule |\n|---|---|\n| trace_name | Original native filename without extension; joins all 109 events to released archives |\n| trace_type | One of five disturbed trace categories; process_failure contains driver/executor/unknown events |\n| anomaly_type | Six known types plus unknown, kept separately |\n| anomaly_details | CPU impact descriptor; 18 increased_processing_time, 5 no_application_impact, 3 application_crash |\n| root_cause_start/end | Unix seconds, closed interval; 19 process-failure point intervals have equal endpoints |\n| extended_effect_end | Best-effort consequence endpoint, not physical propagation truth; 28 missing values |\n| application id | Documented native trace naming convention, not a separate CSV column |',
        table(types),
        'The 28 absent EEIs comprise 7 burst-until-crash, 12 unknown, 5 CPU no-application-impact, 3 stalled-input and 1 bursty-input events. Absence is not a measured zero effect: crash truncation, no reported application effect and uncertain annotation are distinct. There are no reversed intervals or duplicate ground-truth rows. Durations are elapsed seconds; a zero duration RCI can still contain one native observation.',
        'Two closed-interval overlap pairs touch at a single boundary; none overlap for positive elapsed time. The event-wise audit retains both rows and marks shared times ineligible for unique phase attribution. Original scalar label assignment can overwrite the earlier type at these shared instants.',table(overlap[['trace','event_a','event_b','type_a','type_b','boundary_only']]),
        'Seven metadata-selected native archives (43,256,084 compressed bytes) were inspected for CSV hashes/schema/timestamps and three diagnostic raw channels. They contain 2,283 features. All seven have timestamp gaps; 9_5_1000000_84 also contains one duplicate timestamp. This audit counts observed unique times without imputing detector input. Only 7/93 traces and 9/109 events have renewed raw inspection; remaining raw files and complete feature finiteness are unknown.',table(raw[['trace','rows','unique_timestamps','duplicate_timestamp_rows','non_1s_steps','max_step']]),
        'All three checked process-failure RCIs have exactly one observed native timestamp. The checked burst-until-crash trace ends exactly at its RCI end, has no EEI and no observed recovery; an unknown event in the CPU trace also ends at the recording boundary. Right-censoring is retained.',table(aligned),
        f'Original [SparkManager]({NATIVE}src/data/spark_manager.py) labels the closed union from RCI start through EEI end (or RCI end when absent), ignoring no_application_impact when os.only is requested. [Source defaults]({NATIVE}src/utils/spark.py) and the reproduction notebook use 15s pre/data/label sampling and trace_scaling. Labels use categorical max in each bin and features use aggregated values plus fills; bin timestamp and type id do not preserve phase identity. The higher enum is not anomaly severity.',table(bins[['event_id','anomaly_type','native_rci_observations','rci_occupied_bins','mixed_rci_eei_bins']]),
        f'[DIVAD loader]({DIVAD}exathlon/data/managers/spark_manager.py) explicitly resolves duplicate/missing times with 1s max aggregation and ffill/bfill. Missing executor/OS handling and original trace scaling can use later observations. These transformations must have causal availability timestamps before any early-detection claim. DIVAD additionally supports include_extended_effect=False and different os_only relabeling, which are different ground-truth targets.',
        'Source discrepancies remain visible: live official Dataset wiki says 6 stalled-input instances, while raw GT contains 16. The downloaded wiki is unversioned, hashed and not allowed to replace GT. DIVAD metadata contains an executor exception under renamed 5_5_1500000_92, conflicting with its raw-name mapping; executors for 5_5_1000000_92 stay unknown. The default YAML removal comment disagrees with actual REMOVAL_OPTIONS (source code removes 1_0_10000_17). No silent source correction is performed.'
    ])
    write('TYPE_APP_CONTEXT_COVERAGE.md',[
        '# Type × app × context coverage',
        'Unit: annotation events nested in native traces, applications and shared cluster executions. Repeated events within one run and concurrent apps are not independent scientific replications. Shared-start candidates are preserved in results/shared_start_candidates.csv; unequal starts can still share a batch. Source families from D0 do not substitute for native identity here.',
        table(coverage),
        'Every known type spans multiple apps, so type is not a deterministic function of app. Many type×app cells have only one or two events and cannot be independent scientific strata. Resource configuration is more severely tied to trace type: documented memory is usually 30GB for normal versus 9/15GB for disturbed runs; executor counts and input-rate corrections also change. The context inventory uses actual DIVAD declarations, preserves the one executor conflict and distinguishes nominal filenames from corrected rates. It is documentation, not independently reverified cluster settings.',
        table(normal[['app','undisturbed_runs','disturbed_runs','documented_normal_contexts','documented_test_contexts','disturbed_traces_with_exact_normal_context','disturbed_traces_with_unknown_context','disturbed_traces_with_matching_input_rate_only']]),
        'No one of the 33 disturbed traces with known full context has an exact same-app normal tuple (corrected input rate,batch interval,executors,memory); the remaining disturbed trace has uncertain executor context. A failed exact joint match is not proof that the application lacks all useful normal support: input-rate-only matches exist. Application8 has no undisturbed runs; app7 has no disturbed runs. Original all-app experiments exclude both and cover eight apps, not all ten.',
        'Original dataset split puts whole undisturbed runs in train and disturbed runs in test; its modeling split subsequently uses stratified windows with seed21 and normal validation/modeling-test proportions .15/.15. DIVAD has unsupervised/generalization/weakly setups and different time/random validation policies; the YAML alone is not a run manifest. E0 performs no train/validation/test split and no threshold fitting.',
        'Bounded native normal examples have observed raw-channel location/scale differences, shown below for diagnostic context only. These are raw telemetry, **not detector scores** and not evidence of calibration dominance. The three selected normal runs do not establish the distribution across all 59 normal runs; −1 sentinel values are counted and excluded from these descriptive nonnegative raw statistics.',table(variation[['trace','metric','finite_nonnegative_count','minus_one_sentinel_count','median','q25','q75']]),
        'Type footprint hypotheses are documented interventions, not empirical modern-detector failures: burst/stall change input supply; CPU contention changes host resource availability and sometimes has no application impact; driver/executor injections are instantaneous and consequences persist; unknown has no known intervention. F4 needs score/feature attribution with context and crash controls before calling any footprint observed.'
    ])
    artifacts=read('artifact_tree_inventory.json')
    write('SCORE_ARTIFACT_INVENTORY.md',[
        '# Official score-artifact inventory',
        'Search scope: immutable untruncated default-branch trees, official release APIs, README links and original reproducibility notebook. Exathlon and DIVAD have no GitHub releases/assets at audit time. No native per-trace score arrays, thresholds, checkpoints or machine-readable AD1–AD4 output tables were found in these snapshots. This is a bounded public-artifact search, not a claim private/external outputs do not exist.',
        table(pd.DataFrame([{'repo':a['repo'],'tree_entries':a['tree_entries'],'truncated':a['truncated'],'score_or_model_files':len(a['potential_score_model_or_csv_paths']),'notebook_cells_with_output':sum(n['cells_with_output'] for n in a['notebooks'])} for a in artifacts])),
        'The Exathlon notebook computes trace_scores and reads locally generated evaluation CSVs/models; its code cells have no saved output. A reproducible generation recipe is not a released score bundle. Published PDF figures and aggregate/type F1 or peak-PR values cannot reconstruct event-level score continuity, normal trace scales, first alarm or RCI-vs-EEI contrast. Prior-art external repo searches also found no admissible native score manifest: see PRIOR_ART_OVERLAP.md and provenance.',
        f'Original [AE reconstruction readout]({NATIVE}src/scoring/reconstruction/reconstruction_scorers.py) averages scores of enclosing windows back onto each member record. Interior targets depend on later window ends. The inspected method is executed only against constant dummy window scores in scripts/readout_trace.py: W40,N100 gives future availability up to39 steps, and its actual tail division leaves the last constant-input readout at0.025 rather than1. This is a source-readout fixture, not a detector inference, a released score reproduction or a measured artifact contribution. The native 15s default could multiply step latency if that configuration generated the result; no manifest seals it.',
        'Native LSTM prediction is statically implemented but has its own warmup/target alignment. DIVAD TranAD provides a right-edge window scorer but the base wrapper applies EWMA and masked warmup; its published peak F1 uses test labels. Neither is automatically admissible under E0 causal raw-score/normal-only threshold requirements. AE enclosing-window score and original future fills cannot be relabeled as zero-latency early alarms.',
        'Missing required bundle: raw native identity/hash; original t and score target; available_at; complete unpadded raw scores; normal fit/validation/calibration/heldout-normal trace membership; preprocessing/source/checkpoint hashes; fixed architecture/window/training seed/budget; unsupervised threshold provenance; every event and separate RCI/EEI masks. Score arrays with only transformed TSB indices or union labels are insufficient.',
        'A bounded rerun is scientifically required to answer the model-failure question when such a bundle cannot be recovered. Conditional candidate panel (maximum4): native Exathlon AE, native LSTM, DIVAD PCA, DIVAD TranAD. No baseline is selected by observed anomaly performance. Existing runtime is Python3.12 arm64 without TensorFlow/torch in the bundled analysis environment; native requirements differ and include unpinned dependencies. This probe is not a proof of impossibility and does not substitute for runtime parity.',
        'This Commit-A protocol freezes the audit and measurement contract, **not a training execution manifest**. No bounded run executes from guessed preprocessing, unsupported native runtime or incomplete raw feature/split seal. Resolving those contracts needs a concrete execution amendment; arbitrary toy retraining or a private PyTorch imitation would not answer the requested native/representative failure comparison. Training remains NOT_RUN; the final evidence branch must retain this limitation.'
    ])
    write('FAILURE_METRICS.md',[
        '# Prospective E0 failure metrics — frozen before any detector results',
        'Exact rules are in provenance/protocol.json and scripts/lifecycle_metrics.py. No detector result, model, threshold or selected test subset was inspected. The helper is tested on artificial boundary fixtures only; it does not train or score telemetry.',
        'RCI=[start,end], including point events. EEI=(end,effect_end], absent if no effect endpoint. Pre-RCI and recovery windows are300 native seconds, excluding all labeled event support; recovery right-censored at trace end. Shared event times are excluded from unique attribution and counted. Coverage uses the epoch-zero native1s grid, including absent timestamps; off-grid score timestamps are rejected. Overlap exclusions count expected native instants even if unobserved, with observed overlap counts reported separately. No observed root alarm with incomplete RCI evidence is N/A, not false. Score absence, future availability, native missing times, mixed-phase sampled bins and zero normal scale are explicit non-estimability, never model failure.',
        '| Metric | Fixed definition |\n|---|---|\n| Root-Cause Capture | Any eligible causal raw score strictly above normal-only threshold during RCI; report eligible support, normal FPR and duration-matched normal false-alarm capture alongside |\n| Effect-Only Detection | Complete eligible native RCI evidence, none alarm; eligible EEI alarm exists. Incomplete RCI or missing EEI -> N/A |\n| Detection Delay | First causal event alarm minus RCI start only with full native event support/no ambiguous overlap; first observed partial alarm stored separately |\n| RCI-vs-EEI contrast | (median RCI − median EEI) / heldout normal calibration IQR; zero IQR -> N/A |\n| Pre-RCI contrast | (median RCI − median pre-RCI normal) / same fixed scale |\n| Raw continuity | Median absolute adjacent score change / normal calibration IQR, only contiguous valid native timestamps |\n| Alarm fragments | Runs of score>threshold, consecutive native1s timestamps; missingness breaks runs |\n| High-score run length | Native seconds in each alarm run; longest run + support counts |\n| Within-event dropout | Valid phase scores at/below threshold divided by eligible scores; missing score fraction separately |\n| Normal calibration | Median/IQR/quantiles, normal heldout FPR by trace/app/context; global vs app threshold only where app ID is available |',
        'Threshold = normal-validation score quantile0.995, linear quantile interpolation. Fit/validation/calibration are normal-only; helper refuses positive calibration labels. No test-anomaly threshold sweep, oracle winner or polarity change. App conditioning requires deployment-visible app ID and supported normal calibration. Per-trace test-label threshold, if ever diagnostic, is ORACLE and excluded from deployment results; none is computed here.',
        'Any-alarm capture in a long interval can occur by chance at nonzero normal false-positive rate. Capture alone never supports a positive gate: raw phase separation and duration-matched heldout-normal alarm references must agree. A point RCI has one instant of score evidence, not a positive-duration scientific segment. Do not widen it into EEI or treat confirmation after onset as a root-time alarm.',
        'Native AD1–AD4 are range-based union-label metrics, with AD3 favoring onset and AD4 penalizing duplicates. They cannot prove effect-only failure or replace RCI/EEI metrics. If later computed, retain native union secondary metrics and phase-specific primary metrics with identical split/scorer provenance. Report joint point AP and range/early/exactly-once behavior; do not choose a result-informed same-AP subset.',
        'Aggregation is descriptive event/trace/app/context hierarchy; shared cluster executions and small1–2-event cells remain explicit. A positive gate needs repeated failure over multiple types/apps and distinct baseline families, no crash/sampling/threshold explanation, preserved raw-score separation, and a residual beyond original Exathlon/DIVAD. No iid p-value, windows-as-N, new model claim or automatic xLSTM choice.'
    ])
    index='| Artifact | Purpose |\n|---|---|\n| [DATA_GROUND_TRUTH_AUDIT.md](DATA_GROUND_TRUTH_AUDIT.md) | Native fields, timestamps, overlap, crash and downsampling |\n| [TYPE_APP_CONTEXT_COVERAGE.md](TYPE_APP_CONTEXT_COVERAGE.md) | Complete type×app coverage and normal support |\n| [PRIOR_ART_OVERLAP.md](PRIOR_ART_OVERLAP.md) | Primary-source occupancy and modern artifacts |\n| [SCORE_ARTIFACT_INVENTORY.md](SCORE_ARTIFACT_INVENTORY.md) | Released-output search and bounded rerun prerequisites |\n| [FAILURE_METRICS.md](FAILURE_METRICS.md) | Prespecified measurement definitions |'
    if final:
        gate={'verdict':'DATA_OR_ARTIFACT_INSUFFICIENT','method_design_GO':False,'detector_models_run':0,'detector_training_runs':0,'RCI_EEI_failure_measured':False,'calibration_dominance_measured':False,'fragmentation_dominance_measured':False,'no_actionable_failure_claimed':False,'bounded_rerun_needed':True,'bounded_rerun_executed':False,'reason':'No admissible per-trace causal score/split/checkpoint bundle; native preprocessing/readout and context support cannot be bypassed with guessed substitutions','STOP_for_reviewer':True}
        (RESULT/'final_gate.json').write_text(json.dumps(gate,indent=2)+'\n')
        missing=[]
        for baseline in ['native_AE','native_LSTM','DIVAD_PCA','DIVAD_TranAD']:
            for f in ['F1_RCI_EEI','F2_fragmentation','F3_calibration','F4_type_context']:
                missing.append({'conditional_candidate':baseline,'analysis':f,'status':'NOT_MEASURED_NO_ADMISSIBLE_SCORE_BUNDLE','metric_value':None,'trained':False})
        (RESULT/'failure_decomposition_status.json').write_text(json.dumps(missing,indent=2)+'\n')
        write('ROOT_CAUSE_EFFECT_ANALYSIS.md',[
            '# Root cause versus extended effect — evidence status',
            '**No detector phase scores or alarms were measured.** RCI/EEI medians, effect-only fractions and delays are N/A for every conditional baseline. Ground-truth boundaries and raw telemetry are not detector output. An NA does not support either failure or success.',
            'The raw audit establishes identifiability constraints:19 point RCIs;28 absent EEIs;two shared boundary instants;observed timestamp gaps;crash at trace end;15s phase mixing;retrospective enclosing-window AE scoring. Three sampled process RCIs each have one native observation. Some positive-duration events have observed EEI support, so this is not a claim that Exathlon can never support a lifecycle analysis.',
            'Type/app coverage is genuine and multiple types span apps, but resource contexts/shared batches and small cells prohibit iid interpretation. CPU no_application_impact events must not be interpreted as model blindness to an application consequence that was not annotated. Unknown intervals cannot supply known fault-mechanism confirmation.',
            'AD1/AD3 paper evidence motivates the question; it does not quantify modern effect-only detection. The narrow phase decomposition is PARTIALLY_STUDIED, not a novelty proof. A bounded causal score recovery/rerun with exact native trace/split/runtime/readout seal is needed before any ROOT_CAUSE_EFFECT_GAP_ACTIONABLE verdict. No new model, precursor method or propagation mechanism is inferred.'
        ])
        write('CALIBRATION_ANALYSIS.md',[
            '# Cross-trace calibration — evidence status',
            '**Normal detector-score location/scale, normal-only thresholds and heldout-normal FPR are NOT_MEASURED.** Raw-channel medians are descriptive telemetry checks; aggregate peak F1 cannot reveal deployed threshold failure. No test-label threshold or per-trace oracle was fitted.',
            'Same-app normal input-rate support is incomplete; exact documented joint resource contexts have no normal counterpart among33 known-context disturbed runs and one trace has conflicting executor metadata. App8 has no normal run. These are context-support confounds, not measured calibration failure or evidence of intact anomaly representation.',
            'Generic global separation and context/domain shifts are ALREADY_EXPLICIT in original Exathlon/DIVAD and modern cloud telemetry literature. The 2026 cloud calibration study also does not establish this Issue’s normal-only calibration contract. A new calibration contribution does not follow.',
            'For a bounded rerun, separate raw-score discrimination from threshold behavior under fixed global and app-visible normal-only quantiles, preserve unknown contexts and hold out complete normal traces. CALIBRATION_FAILURE_DOMINANT requires measured normal baseline shifts together with preserved anomaly separation; neither condition is established here.'
        ])
        write('FRAGMENTATION_ANALYSIS.md',[
            '# Score fragmentation / continuity — evidence status',
            '**Detector raw continuity, alarm run lengths, dropouts and fragment counts are NOT_MEASURED.** The original paper’s LSTM spikes are prior-art evidence, not a new reproduction. Raw telemetry gaps/duplicates are input quality observations, not detector fragmentation.',
            'Original AE enclosing-window averaging, its constant-window tail readout,15s feature/label bins and DIVAD EWMA/warmup masks alter time continuity. The no-model source fixture shows readout behavior without assigning any actual score/AP/AD2/AD3/AD4 gap to it. Do not call a suspected artifact dominant.',
            'Native range/early/exactly-once performance and raw continuity need the same scored trace/split and normal-only threshold. Phase-specific fragments must exclude unresolved overlap/availability and report missing support. TEMPORAL_FRAGMENTATION_DOMINANT is unavailable from aggregate F1 or absent raw outputs.',
            'Generic score spikes, smoothing, voting and range continuity are ALREADY_EXPLICIT. No smoothing method, range objective or xLSTM benefit is proposed.'
        ])
        write('FINAL_GATE.md',[
            '# E0 final gate',
            '**DATA_OR_ARTIFACT_INSUFFICIENT. method_design_GO=false. STOP for reviewer.**',
            'This is an evidence verdict: the requested modern/representative detector lifecycle failure cannot be measured from the admissible public artifacts found. It is not NO_ACTIONABLE_FAILURE, a positive failure gate, or a new reproduction of prior-art model results. All conditional baseline F1–F4 entries remain NOT_MEASURED.',
            'Native labels and bounded raw inspection are useful and sufficient to expose concrete prerequisites:109 events/93 traces;19 point RCIs;28 absent EEIs;boundary overlaps;crash censoring;gapped/duplicate timestamps;type/resource context confounds;15s union-label sampling;future-enclosing-window AE readout and unresolved runtime/split/checkpoint lineage. The dataset is not declared unusable, and label validity is not rejected from visual ambiguity.',
            'TYPE_APP_CONFOUNDED is a secondary caution, not the main verdict: types do cross multiple apps, while joint context support is inadequate. EVALUATION/temporal/calibration dominance is not asserted without score counterfactuals. F2/F3/F4 generic formulations are explicitly occupied, and F1’s residual remains unmeasured and not proved novel.',
            'A bounded rerun is needed if native public score bundles cannot be recovered. The allowed maximum4 candidate families and normal-only seed/threshold/split requirements are recorded prospectively. This audit freeze is not a complete training execution seal: specific raw-feature/split/normal-holdout hashes, fixed native architecture/budget/runtime and an audited causal preprocessing/readout contract remain to be sealed. Training an arbitrary proxy would not resolve those validity conditions. No claim that such a rerun is impossible is made.',
            'Independent read-only review found two prospective helper defects: unobserved overlap delay attribution and off-grid replacement of missing native timestamps. Both were fixed with three failing-then-passing regression fixtures, before any detector result; see [review record](provenance/review.json). These clarify the original native-grid/no-ambiguous-delay contract; they do not change a result-derived protocol.',
            'No training, detector inference, model/threshold selection, sweep, modern-model full benchmark or method design occurred. Only source metadata, raw data summaries and one no-model readout method were executed. Commit/push/report complete the E0 audit evidence branch; await the reviewer’s next task for score recovery or a concrete bounded execution amendment.'
        ])
        index+='\n| [ROOT_CAUSE_EFFECT_ANALYSIS.md](ROOT_CAUSE_EFFECT_ANALYSIS.md) | F1 identifiability and unmeasured score fields |\n| [CALIBRATION_ANALYSIS.md](CALIBRATION_ANALYSIS.md) | F3 support/occupancy limits |\n| [FRAGMENTATION_ANALYSIS.md](FRAGMENTATION_ANALYSIS.md) | F2 score-contract limits |\n| [FINAL_GATE.md](FINAL_GATE.md) | Single evidence gate and STOP |'
    write('README.md',[
        '# Issue #25 — Exathlon Semantic Failure Audit E0',
        '**DATA_OR_ARTIFACT_INSUFFICIENT — method design withheld; STOP for reviewer.**' if final else '**COMMIT A: source/coverage/prior-art/metric audit freeze. No training execution seal or detector result.**',
        'This audit preserves native root cause intervals (RCI), extended effects (EEI), unknown events, crash censoring and context support. It answers what can be identified from public artifacts before assigning a detector failure or selecting a new method. [Issue #25](https://github.com/kuo1234/xlstm_anomaly/issues/25) authorizes E0 independently of the stopped M0/D0 hypotheses; historical P4/P5/M0-S/D0 results are unchanged.',index,
        'Evidence:109 native annotation events across34 disturbed traces;59 undisturbed runs; seven bounded raw archives inspected, no detector scores recovered. Prior-art inventory reads seven primary papers and official code; bounded absence is not novelty. The declared gate is not proof of model success/failure. Source checksums, full coverage, conditional run decision and unmeasured fields are retained.',
        '[Plan](PLAN.md), [protocol](provenance/protocol.json), [scope](provenance/issue25_scope.json) and provenance ledgers are the review record. Raw assets stay in ignored data/exathlon_e0_sources. The source loader downloads only hashed snapshots and seven43MB raw inspection archives, not the full3GB repository. It does not execute model code.',
        '```sh\nE0_PY=/Users/kuo/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3\n$E0_PY research/exathlon_semantic_failure_e0/scripts/sources.py\n$E0_PY research/exathlon_semantic_failure_e0/scripts/audit_data.py\n$E0_PY research/exathlon_semantic_failure_e0/scripts/readout_trace.py\n$E0_PY research/exathlon_semantic_failure_e0/scripts/test_metrics.py -v\n$E0_PY research/exathlon_semantic_failure_e0/scripts/reports.py'+(' --final' if final else '')+'\n```',
        'No score resampling, interpolation, future fill, native-runtime parity, training/normal calibration or scientific detector failure is silently declared complete. A bounded rerun is needed to produce admissible evidence, after a concrete execution seal; this E0 branch does not invent scores from figures, reconstruct anomaly detector outputs from telemetry or replace native baselines with unverified imitations.'
    ])
    print('final reports' if final else 'audit freeze reports')


if __name__=='__main__':main()
