"""Reporting from sealed/evaluated artifacts only; no policy rerun or tuning."""
import json
from pathlib import Path
import pandas as pd
from p10_step2e_data import ROOT,OUT,sha,save,utc


def table(df):
    def val(v):
        if pd.isna(v):return 'N/A'
        if isinstance(v,float):return f'{v:.4f}'
        return str(v)
    cols=list(df.columns)
    return '| '+' | '.join(cols)+' |\n| '+' | '.join(['---']*len(cols))+' |\n'+'\n'.join('| '+' | '.join(val(v) for v in row)+' |' for row in df.itertuples(index=False,name=None))+'\n'


def main():
    r=OUT/'results';u=pd.read_csv(r/'units.csv');p=pd.read_csv(r/'primary_case_results.csv');prom=pd.read_csv(r/'promotions.csv');lf=pd.read_csv(r/'long_faults.csv');cv=pd.read_csv(r/'physical_segment_cv.csv');d=pd.read_csv(r/'case_deltas.csv');meta=json.loads((OUT/'evaluator_metadata.json').read_text());proof=json.loads((r/'evaluation_start.json').read_text());config=json.loads((OUT/'run/policy_config.json').read_text())
    prim=p[p.policy!='H_hold'];fault=prim[prim.arm=='fault'];sp=prim[prim.arm=='setpoint']
    faulttab=fault.pivot(index='policy',columns='machine',values=['AP','VUS_PR','fault_written_fraction','fault_false_promotions'])
    faulttab.columns=['_'.join(k) for k in faulttab.columns];faulttab=faulttab.reset_index()
    benign=sp[['machine','policy','normal_B_FPR','normal_B_written_fraction','transition_written_fraction','transition_period_promotions','normal_B_safe_promotions','normal_B_max_unwritten_hours']]
    primarylong=lf[(lf.phi_seed==11)&(lf.op=='W1')&lf.policy.isin(['DEph_cv','H_hold'])]
    longtab=primarylong[['machine','policy','n_checkpoints','n_pass_cv','n_pass_conjunction','first_pass_time_hours','was_promoted','first_false_promotion_hours','fraction_fault_written']]
    pm=prom[(prom.policy=='DEph_cv')&(prom.phi_seed==11)&(prom.op=='W1')][['machine','decision_hours','write_first_hours','write_last_hours','fault_written','transition_written','normal_B_written']]
    robust=u[u.policy=='DEph_cv'].groupby(['machine','op']).agg(AP=('AP','mean'),fault_written=('fault_written_fraction','mean'),fault_promotions=('fault_false_promotions','sum'),NORMAL_B_FPR=('normal_B_FPR','mean'),NORMAL_B_written=('normal_B_written_fraction','mean'),early_promotions=('transition_period_promotions','sum'),safe_promotions=('normal_B_safe_promotions','sum')).reset_index()
    summary={'verdict':'TRANSFER_NOT_SUPPORTED','reason':'Frozen conjunction promotes both long faults in W1/W3 and adapts SP1 by promotion during protocol WAIT; no entirely-safe NORMAL_B promotion. W2 avoids fault promotion but starves both SP1 shifts.','primary_fault_false_promotions':int(fault[fault.policy=='DEph_cv'].fault_false_promotions.sum()),'replicate_fault_false_promotions':int(u[u.policy=='DEph_cv'].fault_false_promotions.sum()),'replicate_early_SP_promotions':int(u[u.policy=='DEph_cv'].transition_period_promotions.sum()),'replicate_safe_NORMAL_B_promotions':int(u[u.policy=='DEph_cv'].normal_B_safe_promotions.sum()),'physical_runs':5,'native_seed_families':3,'benign_seed_families':1,'seeds_operators_independent_N':False,'cv_max':.10,'posthoc_rule_or_retuning':False,'rl':False}
    save(r/'verdict.json',summary)
    lines=['# Step 2e — Restricted TEP Fault-vs-Benign Pilot\n\n**TRANSFER_NOT_SUPPORTED — pending review.**\n\nFrozen stabilisation conjunction does not safely distinguish the two source semantics in this restricted pilot. It adapts both SP1 shifts, but does so during the predeclared WAIT interval and also promotes both long faults. This is a negative result for frozen admission logic on the selected simulator cases; no rule rescue or RL experiment.\n',
    '## 1. Source, frozen protocol and selection\n\n[Protocol](PROTOCOL.md), [selector](selection.json), [dataset manifest](dataset_manifest.json) and [evaluator metadata](evaluator_metadata.json). Review [5978181304](https://github.com/kuo1234/xlstm_anomaly/issues/15#issuecomment-5978181304) accepted Step2d audit PASS/full TEP PARTIAL and authorized restricted Step2e. Author thesis [official DTU PDF](https://backend.orbit.dtu.dk/ws/portalfiles/portal/262630763/Thesis_Christopher_Clarc_Reinartz.pdf), Appendix A.3.1–A.3.2 (PDF95–96/printed74–75), establishes nominal pre-event operation, event30h and conservative40h dynamics after the event for SP variation. Source SHA256 `5d4e73b7d676ae77517e509d2f6653a75d151f256d2507bd65746b6d78723d67`. SP: NORMAL_A<30h; TRANSITION[30,70); NORMAL_B>=70. Fault>=30 remains FAULT even if stationary. Source settling statement is conservative population support, not per-sample physical settling annotation. “Early/unsafe SP promotion” below means violating this **predeclared conservative WAIT protocol**, not proof that the process was physically unhealthy at that timestamp. ModeTransition not evaluated; ramp endpoint still not a primary settled truth.\n\nAcquisition and execution on `ssh kuo` / spark-3994 only, raw under remote ignored `data/step2e/`; no local data download, full HDF5 download or mirror. Official DTU v1 DOI `10.11583/DTU.13385936.v1`, CC0. Selected case paths fixed '+json.loads((OUT/'selection.json').read_text())['utc']+' before detector outcomes. Partial official HDF5 range blocks have exact offsets/SHA256 in manifest; complete modefile checksum remains unverified.\n',
    table(pd.DataFrame([{'case':x['id'],'arm':x['arm'],'path':x['path'],'native_seed':x['native_seed']} for x in meta['cases']])),
    '\nAll cases start in Mode1. **The three SP variants share native seed3010001 and byte-identical normal-train arrays.** They are correlated interventions on one benign seed family, not three independent benign replications. Fault seeds21812/20819 differ from the SP seed and each other; this is not a noise-matched fault-vs-benign causal pair. Five physical run files, **three native-seed families / one benign family**, nine seed/operator robustness trajectories each; no independent N=45 or checkpoints. Protocol shorthand “different native seeds” concerns cross-arm pairing and must not be read as independent SP seeds. Primary seed11/W1 per-case results below; all operators/seeds separately in [units.csv](results/units.csv).\n',
    'Train actual time<20h:399SP/400fault points, M0 first80%, final20% tau q.99. Scaler fit on full normal train only, same Step2b/c convention; source-normal20–30h held out in test. No test normalization/threshold fitting; original53 channels, constants preserved, train-sd floor.02/clipping20. φ dimension-only53×8=424/dk128, seeds11/22/33. W1 kNN5; W2 f=.995; W3 beta=.1. Seven frozen policies and H_hold reference. Rule `self<=1 AND stat<=.5 AND cv<=.10`; block16, checkpoint256/every128/trail256, age512 arm and clean-gap executable semantics unchanged. No model/feature/threshold selection. At3min cadence: block.8h,256=12.8h,128=6.4h,512=25.6h.\n',
    '## 2. Seal and evaluator chronology\n\nProtocol/code/subset commit `453ce77` pushed before scoring; observation-only seal commit `572d27bb69f61cdde4669a267377f326ffcdf74c` pushed before evaluation. [Seal](run/seal.json) SHA256 `'+proof['seal_sha256']+'`, labels_read_by_runner=0, prior_source_semantic_exposure=true, posthoc=false, cv_max=.10. Evaluator verified remote seal ancestry and all artifact/code/raw hashes; start '+proof['utc']+'. [Access log](results/label_access_log.json) records five state-generation accesses after the pushed seal. Source labels/metadata were already exposed by audit/review, so **frozen exploratory controlled simulator transfer**, not strict confirmatory. Paths/SP/IDV/native seed/mode/30–70truth are evaluator-only; policy runner consumes numeric train/test arrays without parsing timestamps or state labels.\n',
    '## 3. Fault detection and contamination (primary seed11/W1)\n\nAP/VUS are fault-vs-source-normal detection metrics. Test has200normal points then1401fault points (prevalence.8751); near-perfect AP here is an easy dense-fault setting, not broad benchmark evidence. All SP cases have no fault labels, so their AP/VUS are **N/A**, never fabricated by labelling transition as a fault. Threshold/no-update prevent fault writes. DEph_cv equals DE_stab in both primary fault trajectories.\n\n'+table(faulttab),
    '\nPer-fault DEph_cv−threshold: IDV1 ΔAP−.031201 / ΔVUS-PR−.026396; IDV2 −.063823 / −.058345. Both directions negative; no single favorable machine driving a pooled positive claim. All five prespecified baseline comparisons are in [case_deltas.csv](results/case_deltas.csv). Robustness-mean threshold deltas are also negative on both faults (AP−.022197/−.033313; VUS−.019560/−.030414).\n',
    '## 4. Actual new-normal adaptation and timing\n\n'+table(benign),
    '\nOn SP1+5%/-5%, threshold freezes after shift (post70 FPR1, write fraction0). DEph_cv improves FPR to.001664/0 and writes97.34%/100% of NORMAL_B. This is **real source-labelled adaptation benefit**, but it was achieved through early promotion, not a correctly delayed safe promotion. Both decisions occur51.95h, writing39.2–51.95h inside the conservative WAIT interval. On SP2+5%, DEph_cv is worse than threshold: post70FPR.051581 vs.021631; NORMAL_B writes31.95% vs73.38%; longest unwritten interval8.8h. Thus behavior depends on the setpoint intervention, despite the same starting trajectory.\n\nNo trajectory in any operator/seed has an entirely-NORMAL_B PROMOTE. First safe-promotion time / delay and post-safe-promotion FPR are N/A; promotion-wait time is right-censored30.05h on the sample-support convention70≤t<100.05 (physical recorded70–100h span30h). This is an action-opportunity measure, **not universal starvation**: SP1 has already adapted via early promotion, always writes100% without a PROMOTE action, and SP2 threshold adapts largely through clean writes. NORMAL_B unwritten fraction / max unwritten interval and FPR separately measure starvation. Full timing, durations/censoring and occupancy ledger in [promotions.csv](results/promotions.csv), [segments.csv](results/segments.csv), [occupancy.csv.gz](results/occupancy.csv.gz).\n\nPrimary DEph_cv decision/write intervals:\n\n'+table(pm),
    '## 5. CV transfer and long-fault checkpoint risk\n\n'+table(cv),
    '\nH_hold seed11/W1: IDV1 fault median CV.014349, IDV2.016313, settled SP1+.010397/SP1−.009820. Fault medians are slightly above the two observed settled-normal medians, so this small directional ordering holds. **Absolute threshold does not separate them**: .10 passes8/9 and9/9 fault checkpoints, while both settled-normal pass3/3. SP2 has no fully-NORMAL_B H_hold checkpoint (no eligible persistent segment then); direction not evaluable for that case. Transition SP1 windows also pass3/4; low CV detects stabilization, not fault-free semantics. Mixed windows retained separately, not assigned by label majority. No pooled checkpoint AUROC or independent-checkpoint evidence claim.\n\nLong-fault table; H_hold is a diagnostic never-promote trajectory, actual DEph_cv is the executed policy:\n\n'+table(longtab),
    '\nIDV1 first CV pass52.75h; conjunction eventually passes at71.95h, promoting256fault points. IDV2 first pass48.75h, actual promotion55.15h writing256fault points. Final fault-written fractions42.26%/75.45% exceed the initial promoted suffix because subsequent admissions continue. A long stationary fault repeatedly supplies passing checkpoints; frozen self/stat/CV conjunction does not establish normality. No threshold, age, trailing window or rescue rule was changed after seeing this.\n',
    '## 6. Operator/seed robustness (means and actual trajectory counts)\n\n'+table(robust),
    '\nDEph_cv: **12 false-fault promotions across18 fault trajectories**, all W1/W3 (3seeds ×2fault cases ×2operators); W2 has0 but does not adapt either SP1 shift (post70FPR1, writes0). Benign SP:12early promotions across27trajectories, all SP1/W1,W3;0entirely-safe NORMAL_B promotions. These are trajectory counts, not12 independent fault events or27 independent benign cases. SP2 across all3operators has higher post70FPR/lower admitted NORMAL_B fraction than threshold in the aggregate; no rescue from the third setpoint.\n\nRelative DE_stab, CV removes only one of13 false-fault promotion events and lowers aggregate fault writes.2805→.2633; benign aggregates are identical. Better than always/age/quarantine in some contamination measures does not satisfy safe transfer versus threshold. Always has0“promotion”events but100%fault writes, so promotion count alone is not memory safety. Mean across correlated SP variants/seeds/operators is robustness description, not significance evidence.\n',
    '## 7. Verification, limits and verdict\n\n11 synthetic/contract tests PASS before run: boundaries incl70, fixed config, train-only scaling/constants, runner input isolation, missing/unpushed seal rejection, score-before-write, future invariance, conjunction/trailing256, distinction between no-promotion and unwritten starvation, fixed five-case manifest. Hash/seal ancestry verified before evaluation; no point-adjust, fitting, training or retuning. Reproduction on remote: `PYTHONPATH=data/step2e/runtime python3 scripts/p10_step2e_transfer.py` (committed code prerequisite), push its seal, then same runtime `python3 scripts/p10_step2e_eval.py`; pinned vus0.0.6/window100. Report script only reads evaluated results. Source/thesis and VUS runtime stay on remote; score traces are tracked, raw observations ignored.\n\nLimits: one operating mode; one benign seed family, two fault seeds/types, fixed magnitudes/ramp10h; no independent benign held-out seed; short normal calibration; constants and scaling inherited; physical-time12.8h checkpoint/trail; partial HDF5 checksum verification only; conservative source-settling window not per-run exact settling annotation. No interpolation/rate ablation, normal-B labels on faults, hidden classifier or RL. These limits narrow the negative result to this pilot, rather than establish universal non-identifiability.\n\n**TRANSFER_NOT_SUPPORTED.** Frozen rule admits stable faults and gives SP1 benefit by violating the conservative timing protocol; SP2 does not rescue the trade-off, and W2 protection accompanies SP1 starvation. There is now source-grounded evidence for both poisoning and new-normal starvation, but this task does **not** authorize learned stopping/RL. Stop after Step2e; await reviewer decision on external evidence, additional preregistered validation or repositioning.\n']
    (OUT/'STEP2E_RESTRICTED_TEP.md').write_text('\n'.join(lines))
    save(r/'report_verification.json',{'utc':utc(),'tests_passed':11,'seal_sha256':proof['seal_sha256'],'verdict':summary,'result_hashes':{str(p.relative_to(r)):sha(p) for p in r.rglob('*') if p.is_file() and p.name!='report_verification.json'}})
    print(json.dumps(summary,indent=2))

if __name__=='__main__':main()
